/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;

/**
 *
 * @author jaime
 */
public class ListadoPorComida extends javax.swing.JDialog {

    /**
     * Creates new form ListadoPorComida
     */
    String rutaV;
    public ListadoPorComida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         rutaV = "src/datos/Ventas.txt";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Comidas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmdListar = new javax.swing.JButton();
        cmdRegresar = new javax.swing.JButton();
        rbH = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        rbB = new javax.swing.JRadioButton();
        rbD = new javax.swing.JRadioButton();
        rbA = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTablaH.setBackground(new java.awt.Color(0, 0, 0));
        tblTablaH.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblTablaH.setForeground(new java.awt.Color(255, 255, 255));
        tblTablaH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Nombre", "Precio", "Cantidad", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTablaH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTablaHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTablaH);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 530, 260));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 550, 290));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("LISTADO DE VENTAS POR CATEGORIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 350, -1));

        cmdListar.setBackground(new java.awt.Color(255, 255, 255));
        cmdListar.setText("LISTAR");
        cmdListar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cmdListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdListarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 100, 30));

        cmdRegresar.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        cmdRegresar.setForeground(new java.awt.Color(255, 0, 0));
        cmdRegresar.setText("REGRESAR");
        cmdRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        cmdRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 160, 40));

        rbH.setBackground(new java.awt.Color(0, 0, 0));
        Comidas.add(rbH);
        rbH.setForeground(new java.awt.Color(255, 255, 255));
        rbH.setText("Hamburguesas");
        jPanel1.add(rbH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        rbP.setBackground(new java.awt.Color(0, 0, 0));
        Comidas.add(rbP);
        rbP.setForeground(new java.awt.Color(255, 255, 255));
        rbP.setText("Pollos");
        jPanel1.add(rbP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        rbB.setBackground(new java.awt.Color(0, 0, 0));
        Comidas.add(rbB);
        rbB.setForeground(new java.awt.Color(255, 255, 255));
        rbB.setText("Bebidas");
        jPanel1.add(rbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        rbD.setBackground(new java.awt.Color(0, 0, 0));
        Comidas.add(rbD);
        rbD.setForeground(new java.awt.Color(255, 255, 255));
        rbD.setText("Desayunos");
        jPanel1.add(rbD, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        rbA.setBackground(new java.awt.Color(0, 0, 0));
        Comidas.add(rbA);
        rbA.setForeground(new java.awt.Color(255, 255, 255));
        rbA.setText("Acompañamientos");
        jPanel1.add(rbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(573, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblTablaHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTablaHMouseClicked

    }//GEN-LAST:event_tblTablaHMouseClicked

    private void cmdListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListarActionPerformed
        String h ="Hamburguesas";
        String b = "Bebidas";
        String d = "Desayunos";
        String p = "Pollos";
        String a = "Acompañamientos";
        if(rbH.isSelected()){
            Helper.listadoPorComida(tblTablaH, rutaV, h); 
        }
        if(rbB.isSelected()){
            Helper.listadoPorComida(tblTablaH, rutaV, b);
        }
        if(rbD.isSelected()){
            Helper.listadoPorComida(tblTablaH, rutaV, d);
        }
        if(rbP.isSelected()){
            Helper.listadoPorComida(tblTablaH, rutaV, p);
        }
        if(rbA.isSelected()){
            Helper.listadoPorComida(tblTablaH, rutaV, a);
        }
    }//GEN-LAST:event_cmdListarActionPerformed

    private void cmdRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegresarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_cmdRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoPorComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoPorComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoPorComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoPorComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoPorComida dialog = new ListadoPorComida(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Comidas;
    private javax.swing.JButton cmdListar;
    private javax.swing.JButton cmdRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbA;
    private javax.swing.JRadioButton rbB;
    private javax.swing.JRadioButton rbD;
    private javax.swing.JRadioButton rbH;
    private javax.swing.JRadioButton rbP;
    private javax.swing.JTable tblTablaH;
    // End of variables declaration//GEN-END:variables
}
